name: Pipeline
on:
    push:
        branches:
            - master

    pull_request:
        branches:
            - master

jobs:
    testsuite:
        name: Testes Automatizados
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version: ["8.1", "8.2"]

        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, json, intl

            - name: checkout
              uses: actions/checkout@v2

            - name: Composer Install
              run: |
                  composer install --no-progress -o --no-ansi --no-interaction

            - name: Check php code style
              run: |
                  composer insights:ci

            - name: Rodando Pest
              run: |
                  composer test
